export const songs = [
  'Goodbye Sea',
  'Ultimate July',
  'Pure August',
  'My November',
  'Earning Rest',
  'Quiet Life',
  'Calm Piano',
  'The Time Has Come Again For Affair',
  'All Into Melody',
  'The Sunset',
  'The Stories',
  'Castle Of Focus',
  'Wonderous Acts',
  'Winter Torch',
  'Old Drink',
  'Close Teenage',
  'First Beetle',
  'Walk With Heaven',
  'Afraid Of Dreamer',
  'Traditional Rebellion',
];
export const artists = [
  'Free Earth 🌎',
  'Buff July',
  'Philosophy Favourites',
  'Pink Masters',
  'Sunshine Channel',
  'Slow Emotions',
  'Worried Start',
  'Favourite Functions',
  'Invisible Piano 🎹',
  'Long With Blues',
  'Pure Country Rocks',
  'Ultimate Classics',
  'Shoegaze Hill',
  '👠💄 Women Of Masters',
  'Kind Of Garden',
  'Drink For Autumn',
  'Next Hometown',
  'Musical Fires',
  'Urban Heroes',
  'Journey To Bing',
];
